### ISSUE TITLE
Blank application window (0.7.0 / Windows 11)

### ISSUE THREAD

**Issue by enigma-x** [adriankumpf/tesla_auth#62] opened 2023-05-17 18:56 UTC
Using tesla_auth 0.7.0 on fully up to date Windows 11 results in a blank application window.

Windows 11 Pro / 22H2
Build: 22621.1702
Windows Feature Experience Pack 1000.22641.1000.0

Edge: Version 113.0.1774.42 (Official build) (64-bit)

Using version 0.6.3 on the system above works fine.

**Comment by adriankumpf** [comment] 2023-05-23 10:02
Sounds like a duplicate of #63 which is fixed in v0.8.0. I'll close this for now.

**Closed by adriankumpf** 2023-05-23 10:02 UTC
